### ISSUE TITLE
Always set timeout to hide the help

### ISSUE THREAD

**Issue by kamataryo** [tilecloud/mbgl-gesture-handling#3]
No timeout (NG):
1. Do wheel on the map container element
=> The help element remains forever. I believe that that this case should be fixed.

timeout (OK):
1. Do wheel on the map container element
2. Do wheel on the help element
=> The help element will hide properly.

**Comment by miya0001** [comment]
> No timeout (NG):
>
>    Do wheel on the map container element
>    => The help element remains forever. I believe that that this case should be fixed.

It is same behavior with the google map.
(Key is not same.)

**Comment by miya0001** [comment]
Ah, also, the help container will be hide if user do wheel + [alt] immediately.
